### ISSUE TITLE
bug of private quote messages

### ISSUE THREAD

**Issue by Acacia415** [LyoSU/quote-bot#176]
"In private messages, you can forward several messages to me at once and I will make a quote from them."
It seems that this feature has changed. Previously, forwarding several messages would merge the n messages into one from the beginning, but now it generates n quotes. Could this feature be changed back?

**Comment by LyoSU** [comment]
I know about this problem. I will try to fix it in the future

**Comment by LyoSU** [comment]
I know about this problem. I will try to fix it in the future

**Comment by LyoSU** [comment]
fixed

**Comment by Acacia415** [comment]
Awesome, thanks 🙏.
