### ISSUE TITLE
[Feature Request] Use default Telegram colors for 404 avatars.

### ISSUE THREAD

**Issue by Kylmakalle** [LyoSU/quote-bot#4]
- Export current colors from any official client
- Use Algorithm from one of the official client to set first letters of `forward_sender_name` in avatar circle

**Comment by LyoSU** [comment]
Я уже использую официальные цвета и так, только чуть поменял их, потому что стандартные слишком яркие. https://github.com/LyoSU/quote-bot/blob/master/utils/quote-generate.js#L393
На счет первых букв подумаю. Изначально я так и сделал, но результат не понравился.

**Comment by LyoSU** [comment]
Это выполнено уже :)
